spring:
  #Database settings
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clearsolutions
    username: ${POSTGRES_NAME}
    password: ${POSTGRES_PASS}